#!/bin/bash

# Install GitHub CLI

(type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
&& sudo mkdir -p -m 755 /etc/apt/keyrings \
&& wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
&& sudo apt update \
&& sudo apt install gh -y

sudo apt update
sudo apt install gh

# Prompt user for issue title and body


gh extension install valeriobelli/gh-milestone


gh milestone create --title "Front-end"  --description "This is a description" --due-date ""
gh milestone create --title "Back-end"  --description "This is a description" --due-date ""
gh milestone create --title "Design"  --description "This is a description" --due-date ""








# Create issue using gh command
gh issue create --title "" --body ""
gh issue create --title "faire le swagger" --body ""
gh issue create --title "faire le design" --body ""
gh issue create --title "faire le back" --body ""


