#!/bin/bash

## Add milestone extension


gh extension install valeriobelli/gh-milestone

## Create Milestones
gh milestone create --title "Front-end"  --description "This is a description" --due-date ""
gh milestone create --title "Back-end"  --description "This is a description" --due-date ""
gh milestone create --title "Design"  --description "This is a description" --due-date ""


# Delete all default label
gh label delete bug --yes
gh label delete documentation --yes
gh label delete duplicate --yes
gh label delete enhancement --yes
gh label delete "good first issue" --yes
gh label delete "help wanted" --yes
gh label delete invalid --yes
gh label delete question --yes
gh label delete wontfix --yes

# Create labels

gh label create front --color 0356fc
gh label create back --color fcdb03
gh label create design --color 03fc39
gh label create urgent --color fc0303
gh label create ci-problem --color be03fc
gh label create bug-to-fix --color fc0398
gh label create documentation --color fc0ff8


# Create issue using gh command
gh issue create --title "design des pages" --body "" --label "design"
gh issue create --title "faire le swagger" --body "" --label "documentation"
